; HEADER_BLOCK_START
; generated by OrcaSlicer 2.3.1 on 2026-03-05 at 11:02:00
; total layer number: 51
; filament_density: 1.24
; filament_diameter: 1.75
; max_z_height: 10.00
; HEADER_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 48x48 196
; iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAWUlEQVR4Ae3PMRGAMBAAwddAgQHEUN
; HTYQUF9KhNNKT4T4q9mROwEZIkDbZd55txVHX8X8s4qgIAAAAAAAAAAACYB9ifu2UcVQEAAAAAAAAA
; AADMA0iStEodtZlcov+exGQAAAAASUVORK5CYII=
; thumbnail end
; THUMBNAIL_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 300x300 1804
; iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAFDklEQVR4Ae3UoU1DAQBF0e9xCBbAIt
; gChcexSifAM22bb5s+f5uck9wNXt5xAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPI3X76+L9KgDSs5Rvv//XaX7HBY5Dksrh0WOw9LKYZ
; HjsLRyWOQ4LK0cFjkOSyuHRY7D0sphkeOwtHJY5DgsrRwWOQ5LK4dFjsPSymGR47C0cljkOCytHBY5
; Dksrh0WOw9LKYZHjsLRyWOQ4LK0cFjkOSyuHRY7D0sphkeOwtHJY5DgsrRwWOQ5LK4dFjsPSymGR47
; C0cljkOCytHBY5Dksrh0WOw9LKYZHjsLRyWOQ4LK0cFjkOSyuHRY7D0sphkeOwtHJY5DgsrRwWOQ5L
; K4dFjsPSymGR47C0cljkOCytHBY5Dksrh0WOw9LKYZHjsLRyWOQ4LK0cFjkOSyuHRY7D0sphkeOwtH
; JY5DgsrRwWOQ5LK4dFjsPSymGR47C0cljkOCytHBY5Dksrh0WOw9LKYZHjsLRyWOQ4LK0cFjkOSyuH
; RY7D0sphkeOwtHJY5DgsrRwWOQ5LK4dFjsPSymGR47C0cljkOCytHBY5Dksrh0WOw9LKYZHjsLRyWO
; Q4LK0cFjkOSyuHRY7D0sphkeOwtHJY5DgsrRwWOQ5LK4dFjsPSymGR47C0cljkOCytHBY5Dksrh0WO
; w9LKYZHjsLRyWOQ4LK0cFjkOSyuHRY7D0sphkeOwtHJY5DgsrRwWOQ5LK4dFjsPSymGR47C0cljkOC
; ytHBY5Dksrh0WOw9LKYZHjsLRyWOQ4LK0cFjkOSyuHRY7D0sphkeOwtHJY5DgsrRwWOQ5LK4dFjsPS
; ymGR8/L5cXn7/blK953bOKDEYWnlsMhxWFo5LHIcllYOixyHpZXDIsdhaeWwyHFYWjkschyWVg6LHI
; ellcMix2Fp5bDIcVhaOSxyHJZWDosch6WVwyLHYWnlsMhxWFo5LHIcllYOixyHpZXDIsdhaeWwyHFY
; WjkschyWVg6LHIellcMix2Fp5bDIcVhaOSxyHJZWDosch6WVwyLHYWnlsMhxWFo5LHIcllYOixyHpZ
; XDIsdhaeWwyHFYWjkschyWVg6LHIellcMix2Fp5bDIcVhaOSxyHJZWDosch6WVwyLHYWnlsMhxWFo5
; LHIcllYOixyHpZXDIsdhaeWwyHFYWjkschyWVg6LHIellcMix2Fp5bDIcVhaOSxyHJZWDosch6WVwy
; LHYWnlsMhxWFo5LHIcllYOixyHpZXDIsdhaeWwyHFYWjkschyWVg6LHIellcMix2Fp5bDIcVhaOSxy
; HJZWDosch6WVwyLHYWnlsMhxWFo5LHIcllYOixyHpZXDIsdhaeWwyHFYWjkschyWVg6LHIellcMix2
; Fp5bDIcVhaOSxyHJZWDosch6WVwyLHYWnlsMhxWFo5LHIcllYOixyHpZXDIsdhaeWwyHFYWjkschyW
; Vg6LHIellcMix2Fp5bDIcVhaOSxyHJZWDosch6WVwyLHYWnlsMhxWFo5LHIcllYOixyHpZXDIsdhae
; WwyHFYWjkschyWVg6LHIellcMix2Fp5bDIcVhaOSxyzlFKjzoAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACexg3DCaLHU2zJpgAAAABJRU
; 5ErkJggg==
; thumbnail end
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 0.60mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.40mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.60mm

; EXECUTABLE_BLOCK_START
M73 P0 R3
M201 X10000 Y10000 Z500 E800
M203 X500 Y500 Z20 E60
M204 P10000 R1000 T10000
M205 X20.00 Y20.00 Z10.00 E5.00 ; sets the jerk limits, mm/sec
;TYPE:Custom
G21 ;
G90 ; use absolute coordinates
M83 ; extruder relative mode
M204 S10000 T1000
M104 S220 ; set extruder temp
M140 S55 ; set bed temp
M190 S55 ; wait for bed temp
M109 S220 ; wait for extruder temp
G92 E0.0
G28 X0 Y0 ; home
G28 Z0 ; home
G1  Z5 F1000 ; move print head up
G90
G21
M83 ; use relative distances for extrusion
; Filament gcode
M106 S0 ; disable fan
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.2
G92 E0

G1 Z.55 F3600 ; move to next layer (0)
;AFTER_LAYER_CHANGE
;0.2
;_SET_FAN_SPEED_CHANGING_LAYER
M204 S600 ; adjust acceleration
M205 X4 Y4 ; adjust jerk
; printing object Cube id:0 copy 0
G1 E-.9 F3000 ; retract
G1 Z1.05 F3600 ; lift Z
G1 X46.677 Y46.677 ; move to first perimeter point
G1 Z.55 ; move to first perimeter point
G1 Z.2 ; force restore Z after unknown last pos
G1 E.95 F900 ;  ; unretract
;TYPE:Outer wall
;WIDTH:0.6
G1 F600
M73 P1 R3
G1 X50 Y43.353 E.21771 ; perimeter
G1 X56.647 Y50 E.43542 ; perimeter
G1 X50 Y56.647 E.43542 ; perimeter
G1 X43.353 Y50 E.43542 ; perimeter
M73 P2 R3
G1 X46.648 Y46.705 E.21586 ; perimeter
; stop printing object Cube id:0 copy 0
M106 S255 ; enable fan
;LAYER_CHANGE
;Z:0.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.4
G92 E0

G1 Z0.200 F3600 ; move to next layer (1)
;AFTER_LAYER_CHANGE
;0.4
;_SET_FAN_SPEED_CHANGING_LAYER
M104 S200 ; set nozzle temperature
; printing object Cube id:0 copy 0
G1 F600
G1 Z0.269 X50 Y43.353 E0.02768 ; perimeter
G1 Z0.407 X56.647 Y50 E0.16375 ; perimeter
M73 P3 R3
G1 Z0.544 X50 Y56.647 E0.27260 ; perimeter
G1 Z0.682 X43.353 Y50 E0.38146 ; perimeter
M73 P4 R3
G1 Z0.750 X46.648 Y46.705 E0.21586 ; perimeter
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:0.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.6
G92 E0

G1 Z0.750 F3600 ; move to next layer (2)
;AFTER_LAYER_CHANGE
;0.6
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z0.775 X50 Y43.353 E.21956 ; perimeter
G1 Z0.824 X56.505 Y49.859 E.42616 ; perimeter
M73 P5 R3
G1 Z0.825 X56.647 Y50 E.00926 ; perimeter
G1 Z0.875 X50 Y56.647 E.43542 ; perimeter
G1 Z0.925 X43.353 Y50 E.43542 ; perimeter
M73 P6 R3
G1 Z0.950 X46.648 Y46.705 E.21586 ; perimeter
M73 P6 R2
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:0.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.8
G92 E0

G1 Z0.950 F3600 ; move to next layer (3)
;AFTER_LAYER_CHANGE
;0.8
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z0.975 X50 Y43.353 E.21956 ; perimeter
G1 Z1.023 X56.364 Y49.717 E.41689 ; perimeter
M73 P7 R2
G1 Z1.025 X56.647 Y50 E.01853 ; perimeter
G1 Z1.075 X50 Y56.647 E.43542 ; perimeter
G1 Z1.125 X43.353 Y50 E.43542 ; perimeter
M73 P8 R2
G1 Z1.150 X46.648 Y46.705 E.21586 ; perimeter
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:1
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;1
G92 E0

G1 Z1.150 F3600 ; move to next layer (4)
;AFTER_LAYER_CHANGE
;1
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z1.175 X50 Y43.353 E.21956 ; perimeter
G1 Z1.222 X56.223 Y49.576 E.40763 ; perimeter
M73 P9 R2
G1 Z1.225 X56.647 Y50 E.02779 ; perimeter
G1 Z1.275 X50 Y56.647 E.43542 ; perimeter
G1 Z1.325 X43.353 Y50 E.43542 ; perimeter
M73 P10 R2
G1 Z1.350 X46.648 Y46.705 E.21586 ; perimeter
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:1.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;1.2
G92 E0

G1 Z1.350 F3600 ; move to next layer (5)
;AFTER_LAYER_CHANGE
;1.2
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z1.375 X50 Y43.353 E.21956 ; perimeter
G1 Z1.421 X56.081 Y49.434 E.39836 ; perimeter
M73 P11 R2
G1 Z1.425 X56.647 Y50 E.03706 ; perimeter
G1 Z1.475 X50 Y56.647 E.43542 ; perimeter
G1 Z1.525 X43.353 Y50 E.43542 ; perimeter
M73 P12 R2
G1 Z1.550 X46.648 Y46.705 E.21586 ; perimeter
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:1.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;1.4
G92 E0

G1 Z1.550 F3600 ; move to next layer (6)
;AFTER_LAYER_CHANGE
;1.4
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z1.575 X50 Y43.353 E.21956 ; perimeter
G1 Z1.620 X55.94 Y49.293 E.3891 ; perimeter
M73 P13 R2
G1 Z1.625 X56.647 Y50 E.04632 ; perimeter
G1 Z1.675 X50 Y56.647 E.43542 ; perimeter
G1 Z1.725 X43.353 Y50 E.43542 ; perimeter
M73 P14 R2
G1 Z1.750 X46.648 Y46.705 E.21586 ; perimeter
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:1.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;1.6
G92 E0

G1 Z1.750 F3600 ; move to next layer (7)
;AFTER_LAYER_CHANGE
;1.6
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z1.775 X50 Y43.353 E.21956 ; perimeter
G1 Z1.819 X55.798 Y49.151 E.37984 ; perimeter
M73 P15 R2
G1 Z1.825 X56.647 Y50 E.05559 ; perimeter
G1 Z1.875 X50 Y56.647 E.43542 ; perimeter
G1 Z1.925 X43.353 Y50 E.43542 ; perimeter
M73 P16 R2
G1 Z1.950 X46.648 Y46.705 E.21586 ; perimeter
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:1.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;1.8
G92 E0

G1 Z1.950 F3600 ; move to next layer (8)
;AFTER_LAYER_CHANGE
;1.8
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z1.975 X50 Y43.353 E.21956 ; perimeter
G1 Z2.018 X55.657 Y49.01 E.37057 ; perimeter
M73 P17 R2
G1 Z2.025 X56.647 Y50 E.06485 ; perimeter
G1 Z2.075 X50 Y56.647 E.43542 ; perimeter
G1 Z2.125 X43.353 Y50 E.43542 ; perimeter
M73 P18 R2
G1 Z2.150 X46.648 Y46.705 E.21586 ; perimeter
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;2
G92 E0

G1 Z2.150 F3600 ; move to next layer (9)
;AFTER_LAYER_CHANGE
;2
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z2.175 X50 Y43.353 E.21956 ; perimeter
G1 Z2.217 X55.515 Y48.869 E.36131 ; perimeter
M73 P19 R2
G1 Z2.225 X56.647 Y50 E.07411 ; perimeter
G1 Z2.275 X50 Y56.647 E.43542 ; perimeter
G1 Z2.325 X43.353 Y50 E.43542 ; perimeter
M73 P20 R2
G1 Z2.350 X46.648 Y46.705 E.21586 ; perimeter
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:2.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;2.2
G92 E0

G1 Z2.350 F3600 ; move to next layer (10)
;AFTER_LAYER_CHANGE
;2.2
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z2.375 X50 Y43.353 E.21956 ; perimeter
G1 Z2.416 X55.374 Y48.727 E.35204 ; perimeter
M73 P21 R2
G1 Z2.425 X56.647 Y50 E.08338 ; perimeter
G1 Z2.475 X50 Y56.647 E.43542 ; perimeter
G1 Z2.525 X43.353 Y50 E.43542 ; perimeter
G1 Z2.550 X46.648 Y46.705 E.21586 ; perimeter
M73 P22 R2
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:2.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;2.4
G92 E0

G1 Z2.550 F3600 ; move to next layer (11)
;AFTER_LAYER_CHANGE
;2.4
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z2.575 X50 Y43.353 E.21956 ; perimeter
G1 Z2.615 X55.233 Y48.586 E.34278 ; perimeter
G1 Z2.625 X56.647 Y50 E.09264 ; perimeter
M73 P23 R2
G1 Z2.675 X50 Y56.647 E.43542 ; perimeter
G1 Z2.725 X43.353 Y50 E.43542 ; perimeter
G1 Z2.750 X46.648 Y46.705 E.21586 ; perimeter
M73 P24 R2
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:2.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;2.6
G92 E0

G1 Z2.750 F3600 ; move to next layer (12)
;AFTER_LAYER_CHANGE
;2.6
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z2.775 X50 Y43.353 E.21956 ; perimeter
G1 Z2.814 X55.091 Y48.444 E.33351 ; perimeter
G1 Z2.825 X56.647 Y50 E.10191 ; perimeter
M73 P25 R2
G1 Z2.875 X50 Y56.647 E.43542 ; perimeter
G1 Z2.925 X43.353 Y50 E.43542 ; perimeter
G1 Z2.950 X46.648 Y46.705 E.21586 ; perimeter
M73 P26 R2
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:2.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;2.8
G92 E0

G1 Z2.950 F3600 ; move to next layer (13)
;AFTER_LAYER_CHANGE
;2.8
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z2.975 X50 Y43.353 E.21956 ; perimeter
G1 Z3.012 X54.95 Y48.303 E.32425 ; perimeter
G1 Z3.025 X56.647 Y50 E.11117 ; perimeter
M73 P27 R2
G1 Z3.075 X50 Y56.647 E.43542 ; perimeter
G1 Z3.125 X43.353 Y50 E.43542 ; perimeter
G1 Z3.150 X46.648 Y46.705 E.21586 ; perimeter
M73 P28 R2
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:3
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;3
G92 E0

G1 Z3.150 F3600 ; move to next layer (14)
;AFTER_LAYER_CHANGE
;3
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z3.175 X50 Y43.353 E.21956 ; perimeter
G1 Z3.211 X54.808 Y48.162 E.31499 ; perimeter
G1 Z3.225 X56.647 Y50 E.12044 ; perimeter
M73 P29 R2
G1 Z3.275 X50 Y56.647 E.43542 ; perimeter
G1 Z3.325 X43.353 Y50 E.43542 ; perimeter
G1 Z3.350 X46.648 Y46.705 E.21586 ; perimeter
M73 P30 R2
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:3.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;3.2
G92 E0

G1 Z3.350 F3600 ; move to next layer (15)
;AFTER_LAYER_CHANGE
;3.2
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z3.375 X50 Y43.353 E.21956 ; perimeter
G1 Z3.410 X54.667 Y48.02 E.30572 ; perimeter
G1 Z3.425 X56.647 Y50 E.1297 ; perimeter
M73 P31 R2
G1 Z3.475 X50 Y56.647 E.43542 ; perimeter
G1 Z3.525 X43.353 Y50 E.43542 ; perimeter
G1 Z3.550 X46.648 Y46.705 E.21586 ; perimeter
M73 P32 R2
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:3.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;3.4
G92 E0

G1 Z3.550 F3600 ; move to next layer (16)
;AFTER_LAYER_CHANGE
;3.4
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z3.575 X50 Y43.353 E.21956 ; perimeter
G1 Z3.609 X54.525 Y47.879 E.29646 ; perimeter
G1 Z3.625 X56.647 Y50 E.13896 ; perimeter
M73 P33 R2
G1 Z3.675 X50 Y56.647 E.43542 ; perimeter
G1 Z3.725 X43.353 Y50 E.43542 ; perimeter
G1 Z3.750 X46.648 Y46.705 E.21586 ; perimeter
M73 P34 R2
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:3.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;3.6
G92 E0

G1 Z3.750 F3600 ; move to next layer (17)
;AFTER_LAYER_CHANGE
;3.6
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z3.775 X50 Y43.353 E.21956 ; perimeter
G1 Z3.808 X54.384 Y47.737 E.28719 ; perimeter
G1 Z3.825 X56.647 Y50 E.14823 ; perimeter
M73 P35 R2
G1 Z3.875 X50 Y56.647 E.43542 ; perimeter
G1 Z3.925 X43.353 Y50 E.43542 ; perimeter
G1 Z3.950 X46.648 Y46.705 E.21586 ; perimeter
M73 P36 R2
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:3.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;3.8
G92 E0

G1 Z3.950 F3600 ; move to next layer (18)
;AFTER_LAYER_CHANGE
;3.8
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z3.975 X50 Y43.353 E.21956 ; perimeter
G1 Z4.007 X54.243 Y47.596 E.27793 ; perimeter
G1 Z4.025 X56.647 Y50 E.15749 ; perimeter
M73 P37 R2
G1 Z4.075 X50 Y56.647 E.43542 ; perimeter
G1 Z4.125 X43.353 Y50 E.43542 ; perimeter
M73 P37 R1
G1 Z4.150 X46.648 Y46.705 E.21586 ; perimeter
M73 P38 R1
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;4
G92 E0

G1 Z4.150 F3600 ; move to next layer (19)
;AFTER_LAYER_CHANGE
;4
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z4.175 X50 Y43.353 E.21956 ; perimeter
G1 Z4.206 X54.101 Y47.454 E.26866 ; perimeter
G1 Z4.225 X56.647 Y50 E.16676 ; perimeter
M73 P39 R1
G1 Z4.275 X50 Y56.647 E.43542 ; perimeter
G1 Z4.325 X43.353 Y50 E.43542 ; perimeter
G1 Z4.350 X46.648 Y46.705 E.21586 ; perimeter
M73 P40 R1
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:4.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;4.2
G92 E0

G1 Z4.350 F3600 ; move to next layer (20)
;AFTER_LAYER_CHANGE
;4.2
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z4.375 X50 Y43.353 E.21956 ; perimeter
G1 Z4.405 X53.96 Y47.313 E.2594 ; perimeter
G1 Z4.425 X56.647 Y50 E.17602 ; perimeter
M73 P41 R1
G1 Z4.475 X50 Y56.647 E.43542 ; perimeter
G1 Z4.525 X43.353 Y50 E.43542 ; perimeter
G1 Z4.550 X46.648 Y46.705 E.21586 ; perimeter
M73 P42 R1
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:4.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;4.4
G92 E0

G1 Z4.550 F3600 ; move to next layer (21)
;AFTER_LAYER_CHANGE
;4.4
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z4.575 X50 Y43.353 E.21956 ; perimeter
G1 Z4.604 X53.818 Y47.172 E.25014 ; perimeter
G1 Z4.625 X56.647 Y50 E.18529 ; perimeter
G1 Z4.675 X50 Y56.647 E.43542 ; perimeter
M73 P43 R1
G1 Z4.725 X43.353 Y50 E.43542 ; perimeter
G1 Z4.750 X46.648 Y46.705 E.21586 ; perimeter
M73 P44 R1
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:4.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;4.6
G92 E0

G1 Z4.750 F3600 ; move to next layer (22)
;AFTER_LAYER_CHANGE
;4.6
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z4.775 X50 Y43.353 E.21956 ; perimeter
G1 Z4.803 X53.677 Y47.03 E.24087 ; perimeter
G1 Z4.825 X56.647 Y50 E.19455 ; perimeter
G1 Z4.875 X50 Y56.647 E.43542 ; perimeter
M73 P45 R1
G1 Z4.925 X43.353 Y50 E.43542 ; perimeter
G1 Z4.950 X46.648 Y46.705 E.21586 ; perimeter
M73 P46 R1
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:4.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;4.8
G92 E0

G1 Z4.950 F3600 ; move to next layer (23)
;AFTER_LAYER_CHANGE
;4.8
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z4.975 X50 Y43.353 E.21956 ; perimeter
G1 Z5.002 X53.536 Y46.889 E.23161 ; perimeter
G1 Z5.025 X56.647 Y50 E.20381 ; perimeter
G1 Z5.075 X50 Y56.647 E.43542 ; perimeter
M73 P47 R1
G1 Z5.125 X43.353 Y50 E.43542 ; perimeter
G1 Z5.150 X46.648 Y46.705 E.21586 ; perimeter
M73 P48 R1
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:5
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;5
G92 E0

G1 Z5.150 F3600 ; move to next layer (24)
;AFTER_LAYER_CHANGE
;5
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z5.175 X50 Y43.353 E.21956 ; perimeter
G1 Z5.201 X53.394 Y46.747 E.22234 ; perimeter
G1 Z5.225 X56.647 Y50 E.21308 ; perimeter
G1 Z5.275 X50 Y56.647 E.43542 ; perimeter
M73 P49 R1
G1 Z5.325 X43.353 Y50 E.43542 ; perimeter
G1 Z5.350 X46.648 Y46.705 E.21586 ; perimeter
M73 P50 R1
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:5.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;5.2
G92 E0

G1 Z5.350 F3600 ; move to next layer (25)
;AFTER_LAYER_CHANGE
;5.2
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z5.375 X50 Y43.353 E.21956 ; perimeter
G1 Z5.400 X53.253 Y46.606 E.21308 ; perimeter
G1 Z5.425 X56.647 Y50 E.22234 ; perimeter
G1 Z5.475 X50 Y56.647 E.43542 ; perimeter
M73 P51 R1
G1 Z5.525 X43.353 Y50 E.43542 ; perimeter
G1 Z5.550 X46.648 Y46.705 E.21586 ; perimeter
M73 P52 R1
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:5.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;5.4
G92 E0

G1 Z5.550 F3600 ; move to next layer (26)
;AFTER_LAYER_CHANGE
;5.4
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z5.575 X50 Y43.353 E.21956 ; perimeter
G1 Z5.599 X53.111 Y46.464 E.20381 ; perimeter
G1 Z5.625 X56.647 Y50 E.23161 ; perimeter
G1 Z5.675 X50 Y56.647 E.43542 ; perimeter
M73 P53 R1
G1 Z5.725 X43.353 Y50 E.43542 ; perimeter
G1 Z5.750 X46.648 Y46.705 E.21586 ; perimeter
M73 P54 R1
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:5.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;5.6
G92 E0

G1 Z5.750 F3600 ; move to next layer (27)
;AFTER_LAYER_CHANGE
;5.6
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z5.775 X50 Y43.353 E.21956 ; perimeter
G1 Z5.798 X52.97 Y46.323 E.19455 ; perimeter
G1 Z5.825 X56.647 Y50 E.24087 ; perimeter
G1 Z5.875 X50 Y56.647 E.43542 ; perimeter
M73 P55 R1
G1 Z5.925 X43.353 Y50 E.43542 ; perimeter
G1 Z5.950 X46.648 Y46.705 E.21586 ; perimeter
M73 P56 R1
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:5.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;5.8
G92 E0

G1 Z5.950 F3600 ; move to next layer (28)
;AFTER_LAYER_CHANGE
;5.8
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z5.975 X50 Y43.353 E.21956 ; perimeter
G1 Z5.996 X52.828 Y46.182 E.18529 ; perimeter
G1 Z6.025 X56.647 Y50 E.25014 ; perimeter
G1 Z6.075 X50 Y56.647 E.43542 ; perimeter
M73 P57 R1
G1 Z6.125 X43.353 Y50 E.43542 ; perimeter
G1 Z6.150 X46.648 Y46.705 E.21586 ; perimeter
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;6
G92 E0

G1 Z6.150 F3600 ; move to next layer (29)
M73 P58 R1
;AFTER_LAYER_CHANGE
;6
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z6.175 X50 Y43.353 E.21956 ; perimeter
G1 Z6.195 X52.687 Y46.04 E.17602 ; perimeter
G1 Z6.225 X56.647 Y50 E.2594 ; perimeter
G1 Z6.275 X50 Y56.647 E.43542 ; perimeter
G1 Z6.325 X43.353 Y50 E.43542 ; perimeter
M73 P59 R1
G1 Z6.350 X46.648 Y46.705 E.21586 ; perimeter
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:6.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;6.2
G92 E0

G1 Z6.350 F3600 ; move to next layer (30)
M73 P60 R1
;AFTER_LAYER_CHANGE
;6.2
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z6.375 X50 Y43.353 E.21956 ; perimeter
G1 Z6.394 X52.546 Y45.899 E.16676 ; perimeter
G1 Z6.425 X56.647 Y50 E.26866 ; perimeter
G1 Z6.475 X50 Y56.647 E.43542 ; perimeter
G1 Z6.525 X43.353 Y50 E.43542 ; perimeter
M73 P61 R1
G1 Z6.550 X46.648 Y46.705 E.21586 ; perimeter
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:6.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;6.4
G92 E0

G1 Z6.550 F3600 ; move to next layer (31)
M73 P62 R1
;AFTER_LAYER_CHANGE
;6.4
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z6.575 X50 Y43.353 E.21956 ; perimeter
G1 Z6.593 X52.404 Y45.757 E.15749 ; perimeter
G1 Z6.625 X56.647 Y50 E.27793 ; perimeter
G1 Z6.675 X50 Y56.647 E.43542 ; perimeter
G1 Z6.725 X43.353 Y50 E.43542 ; perimeter
M73 P63 R1
G1 Z6.750 X46.648 Y46.705 E.21586 ; perimeter
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:6.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;6.6
G92 E0

G1 Z6.750 F3600 ; move to next layer (32)
M73 P64 R1
;AFTER_LAYER_CHANGE
;6.6
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z6.775 X50 Y43.353 E.21956 ; perimeter
G1 Z6.792 X52.263 Y45.616 E.14823 ; perimeter
G1 Z6.825 X56.647 Y50 E.28719 ; perimeter
G1 Z6.875 X50 Y56.647 E.43542 ; perimeter
G1 Z6.925 X43.353 Y50 E.43542 ; perimeter
M73 P65 R1
G1 Z6.950 X46.648 Y46.705 E.21586 ; perimeter
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:6.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;6.8
G92 E0

G1 Z6.950 F3600 ; move to next layer (33)
M73 P66 R1
;AFTER_LAYER_CHANGE
;6.8
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z6.975 X50 Y43.353 E.21956 ; perimeter
G1 Z6.991 X52.121 Y45.475 E.13896 ; perimeter
G1 Z7.025 X56.647 Y50 E.29646 ; perimeter
G1 Z7.075 X50 Y56.647 E.43542 ; perimeter
G1 Z7.125 X43.353 Y50 E.43542 ; perimeter
M73 P67 R1
G1 Z7.150 X46.648 Y46.705 E.21586 ; perimeter
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:7
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;7
G92 E0

G1 Z7.150 F3600 ; move to next layer (34)
M73 P68 R1
;AFTER_LAYER_CHANGE
;7
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z7.175 X50 Y43.353 E.21956 ; perimeter
G1 Z7.190 X51.98 Y45.333 E.1297 ; perimeter
G1 Z7.225 X56.647 Y50 E.30572 ; perimeter
G1 Z7.275 X50 Y56.647 E.43542 ; perimeter
G1 Z7.325 X43.353 Y50 E.43542 ; perimeter
M73 P69 R0
G1 Z7.350 X46.648 Y46.705 E.21586 ; perimeter
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:7.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;7.2
G92 E0

G1 Z7.350 F3600 ; move to next layer (35)
M73 P70 R0
;AFTER_LAYER_CHANGE
;7.2
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z7.375 X50 Y43.353 E.21956 ; perimeter
G1 Z7.389 X51.838 Y45.192 E.12044 ; perimeter
G1 Z7.425 X56.647 Y50 E.31499 ; perimeter
G1 Z7.475 X50 Y56.647 E.43542 ; perimeter
G1 Z7.525 X43.353 Y50 E.43542 ; perimeter
M73 P71 R0
G1 Z7.550 X46.648 Y46.705 E.21586 ; perimeter
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:7.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;7.4
G92 E0

G1 Z7.550 F3600 ; move to next layer (36)
M73 P72 R0
;AFTER_LAYER_CHANGE
;7.4
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z7.575 X50 Y43.353 E.21956 ; perimeter
G1 Z7.588 X51.697 Y45.05 E.11117 ; perimeter
G1 Z7.625 X56.647 Y50 E.32425 ; perimeter
G1 Z7.675 X50 Y56.647 E.43542 ; perimeter
G1 Z7.725 X43.353 Y50 E.43542 ; perimeter
M73 P73 R0
G1 Z7.750 X46.648 Y46.705 E.21586 ; perimeter
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:7.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;7.6
G92 E0

G1 Z7.750 F3600 ; move to next layer (37)
M73 P74 R0
;AFTER_LAYER_CHANGE
;7.6
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z7.775 X50 Y43.353 E.21956 ; perimeter
G1 Z7.787 X51.556 Y44.909 E.10191 ; perimeter
G1 Z7.825 X56.647 Y50 E.33351 ; perimeter
G1 Z7.875 X50 Y56.647 E.43542 ; perimeter
G1 Z7.925 X43.353 Y50 E.43542 ; perimeter
M73 P75 R0
G1 Z7.950 X46.648 Y46.705 E.21586 ; perimeter
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:7.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;7.8
G92 E0

G1 Z7.950 F3600 ; move to next layer (38)
M73 P76 R0
;AFTER_LAYER_CHANGE
;7.8
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z7.975 X50 Y43.353 E.21956 ; perimeter
G1 Z7.986 X51.414 Y44.767 E.09264 ; perimeter
G1 Z8.025 X56.647 Y50 E.34278 ; perimeter
G1 Z8.075 X50 Y56.647 E.43542 ; perimeter
G1 Z8.125 X43.353 Y50 E.43542 ; perimeter
M73 P77 R0
G1 Z8.150 X46.648 Y46.705 E.21586 ; perimeter
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;8
G92 E0

G1 Z8.150 F3600 ; move to next layer (39)
;AFTER_LAYER_CHANGE
;8
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z8.175 X50 Y43.353 E.21956 ; perimeter
G1 Z8.185 X51.273 Y44.626 E.08338 ; perimeter
M73 P78 R0
G1 Z8.225 X56.647 Y50 E.35204 ; perimeter
G1 Z8.275 X50 Y56.647 E.43542 ; perimeter
G1 Z8.325 X43.353 Y50 E.43542 ; perimeter
M73 P79 R0
G1 Z8.350 X46.648 Y46.705 E.21586 ; perimeter
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:8.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;8.2
G92 E0

G1 Z8.350 F3600 ; move to next layer (40)
;AFTER_LAYER_CHANGE
;8.2
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z8.375 X50 Y43.353 E.21956 ; perimeter
G1 Z8.384 X51.131 Y44.485 E.07411 ; perimeter
M73 P80 R0
G1 Z8.425 X56.647 Y50 E.36131 ; perimeter
G1 Z8.475 X50 Y56.647 E.43542 ; perimeter
G1 Z8.525 X43.353 Y50 E.43542 ; perimeter
M73 P81 R0
G1 Z8.550 X46.648 Y46.705 E.21586 ; perimeter
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:8.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;8.4
G92 E0

G1 Z8.550 F3600 ; move to next layer (41)
;AFTER_LAYER_CHANGE
;8.4
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z8.575 X50 Y43.353 E.21956 ; perimeter
G1 Z8.583 X50.99 Y44.343 E.06485 ; perimeter
M73 P82 R0
G1 Z8.625 X56.647 Y50 E.37057 ; perimeter
G1 Z8.675 X50 Y56.647 E.43542 ; perimeter
G1 Z8.725 X43.353 Y50 E.43542 ; perimeter
M73 P83 R0
G1 Z8.750 X46.648 Y46.705 E.21586 ; perimeter
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:8.6
;HEIGHT:0.200001
;BEFORE_LAYER_CHANGE
;8.6
G92 E0

G1 Z8.750 F3600 ; move to next layer (42)
;AFTER_LAYER_CHANGE
;8.6
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z8.775 X50 Y43.353 E.21956 ; perimeter
G1 Z8.782 X50.849 Y44.202 E.05559 ; perimeter
M73 P84 R0
G1 Z8.825 X56.647 Y50 E.37984 ; perimeter
G1 Z8.875 X50 Y56.647 E.43542 ; perimeter
G1 Z8.925 X43.353 Y50 E.43542 ; perimeter
M73 P85 R0
G1 Z8.950 X46.648 Y46.705 E.21586 ; perimeter
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:8.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;8.8
G92 E0

G1 Z8.950 F3600 ; move to next layer (43)
;AFTER_LAYER_CHANGE
;8.8
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z8.975 X50 Y43.353 E.21956 ; perimeter
G1 Z8.981 X50.707 Y44.06 E.04632 ; perimeter
M73 P86 R0
G1 Z9.025 X56.647 Y50 E.3891 ; perimeter
G1 Z9.075 X50 Y56.647 E.43542 ; perimeter
G1 Z9.125 X43.353 Y50 E.43542 ; perimeter
M73 P87 R0
G1 Z9.150 X46.648 Y46.705 E.21586 ; perimeter
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:9
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;9
G92 E0

G1 Z9.150 F3600 ; move to next layer (44)
;AFTER_LAYER_CHANGE
;9
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z9.175 X50 Y43.353 E.21956 ; perimeter
G1 Z9.179 X50.566 Y43.919 E.03706 ; perimeter
M73 P88 R0
G1 Z9.225 X56.647 Y50 E.39836 ; perimeter
G1 Z9.275 X50 Y56.647 E.43542 ; perimeter
G1 Z9.325 X43.353 Y50 E.43542 ; perimeter
M73 P89 R0
G1 Z9.350 X46.648 Y46.705 E.21586 ; perimeter
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:9.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;9.2
G92 E0

G1 Z9.350 F3600 ; move to next layer (45)
;AFTER_LAYER_CHANGE
;9.2
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z9.375 X50 Y43.353 E.21956 ; perimeter
G1 Z9.378 X50.424 Y43.777 E.02779 ; perimeter
M73 P90 R0
G1 Z9.425 X56.647 Y50 E.40763 ; perimeter
G1 Z9.475 X50 Y56.647 E.43542 ; perimeter
G1 Z9.525 X43.353 Y50 E.43542 ; perimeter
M73 P91 R0
G1 Z9.550 X46.648 Y46.705 E.21586 ; perimeter
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:9.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;9.4
G92 E0

G1 Z9.550 F3600 ; move to next layer (46)
;AFTER_LAYER_CHANGE
;9.4
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z9.575 X50 Y43.353 E.21956 ; perimeter
G1 Z9.577 X50.283 Y43.636 E.01853 ; perimeter
M73 P92 R0
G1 Z9.625 X56.647 Y50 E.41689 ; perimeter
G1 Z9.675 X50 Y56.647 E.43542 ; perimeter
G1 Z9.725 X43.353 Y50 E.43542 ; perimeter
M73 P93 R0
G1 Z9.750 X46.648 Y46.705 E.21586 ; perimeter
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:9.6
;HEIGHT:0.200001
;BEFORE_LAYER_CHANGE
;9.6
G92 E0

G1 Z9.750 F3600 ; move to next layer (47)
;AFTER_LAYER_CHANGE
;9.6
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z9.775 X50 Y43.353 E.21956 ; perimeter
G1 Z9.776 X50.141 Y43.495 E.00926 ; perimeter
M73 P94 R0
G1 Z9.825 X56.647 Y50 E.42616 ; perimeter
G1 Z9.875 X50 Y56.647 E.43542 ; perimeter
G1 Z9.925 X43.353 Y50 E.43542 ; perimeter
G1 Z9.950 X46.648 Y46.705 E.21586 ; perimeter
M73 P95 R0
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:9.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;9.8
G92 E0

G1 Z9.950 F3600 ; move to next layer (48)
;AFTER_LAYER_CHANGE
;9.8
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F600
G1 Z9.975 X50 Y43.353 E.21956 ; perimeter
G1 Z10.025 X56.647 Y50 E.43542 ; perimeter
G1 Z10.075 X50 Y56.647 E.43542 ; perimeter
M73 P96 R0
G1 Z10.125 X43.353 Y50 E.43542 ; perimeter
G1 Z10.150 X46.648 Y46.705 E.21586 ; perimeter
M73 P97 R0
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:10
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;10
G92 E0

G1 Z10.150 F3600 ; move to next layer (49)
;AFTER_LAYER_CHANGE
;10
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 F1127
G1 Z10.175 X50 Y43.353 E.21956 ; perimeter
G1 Z10.225 X56.647 Y50 E.43542 ; perimeter
G1 Z10.275 X50 Y56.647 E.43542 ; perimeter
M73 P98 R0
G1 Z10.325 X43.353 Y50 E.43542 ; perimeter
G1 Z10.350 X46.648 Y46.705 E.21586 ; perimeter
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:10
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;10
G92 E0

;AFTER_LAYER_CHANGE
;10
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
G1 X50 Y43.353 E0.19188 ; perimeter
G1 X56.647 Y50 E0.27167 ; perimeter
G1 X50 Y56.647 E0.16282 ; perimeter
M73 P99 R0
G1 X43.353 Y50 E0.05396 ; perimeter
G1 X46.648 Y46.705 E0.00000 ; perimeter
; stop printing object Cube id:0 copy 0
G1 E-.63 F3000 ; retract
;WIPE_START
G1 F3600
G1 X47.355 Y45.998 E-.27 ; wipe and retract
;WIPE_END
G1 Z10.85 F3600 ; lift Z
M106 S0 ; disable fan
;TYPE:Custom
; filament end gcode
G1 E-1.0 F2100 ; retract
G92 E0.0
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
G91 ;
G1 Z+5 F3000
G28 X0 Y0 ; park print head
M84 ; disable motors
G90 ;
M73 P100 R0
; EXECUTABLE_BLOCK_END

; filament used [mm] = 87.08
; filament used [cm3] = 0.21
; filament used [g] = 0.26
; filament cost = 0.01
; total filament used [g] = 0.26
; total filament cost = 0.01
; total layers count = 50
; estimated printing time (normal mode) = 3m 11s
; estimated first layer printing time (normal mode) = 1s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 1
; accel_to_decel_factor = 50%
; activate_air_filtration = 0
; activate_chamber_temp_control = 0
; adaptive_bed_mesh_margin = 0
; adaptive_pressure_advance = 0
; adaptive_pressure_advance_bridges = 0
; adaptive_pressure_advance_model = "0,0,0\n0,0,0"
; adaptive_pressure_advance_overhangs = 0
; additional_cooling_fan_speed = 70
; align_infill_direction_to_model = 0
; alternate_extra_wall = 0
; auxiliary_fan = 0
; bbl_calib_mark_logo = 1
; bbl_use_printhost = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 0x0
; bed_mesh_max = 99999,99999
; bed_mesh_min = -99999,-99999
; bed_mesh_probe_distance = 50,50
; before_layer_change_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\nG92 E0\n
; best_object_pos = 0.5,0.5
; bottom_shell_layers = 0
; bottom_shell_thickness = 0
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_density = 100%
; bottom_surface_pattern = monotonic
; bridge_acceleration = 50%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 0.95
; bridge_no_support = 0
; bridge_speed = 50
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_object_gap = 0.1
; brim_type = auto_brim
; brim_width = 2.4
; calib_flowrate_topinfill_special_order = 0
; chamber_temperature = 0
; change_extrusion_role_gcode = 
; change_filament_gcode = 
; close_fan_the_first_x_layers = 1
; complete_print_exhaust_fan_speed = 70
; cool_plate_temp = 35
; cool_plate_temp_initial_layer = 35
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; counterbore_hole_bridging = none
; curr_bed_type = High Temp Plate
; default_acceleration = 600
; default_bed_type = 
; default_filament_colour = ""
; default_filament_profile = 
; default_jerk = 4
; default_junction_deviation = 0
; default_print_profile = 
; deretraction_speed = 15
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 0
; different_settings_to_system = bottom_shell_layers;brim_width;default_acceleration;default_jerk;enable_arc_fitting;gap_infill_speed;gcode_comments;infill_jerk;initial_layer_acceleration;initial_layer_infill_speed;initial_layer_jerk;initial_layer_line_width;initial_layer_speed;inner_wall_acceleration;inner_wall_jerk;inner_wall_speed;internal_solid_infill_pattern;internal_solid_infill_speed;line_width;max_travel_detour_distance;min_skirt_length;outer_wall_acceleration;outer_wall_jerk;outer_wall_line_width;reduce_crossing_wall;seam_position;seam_slope_conditional;seam_slope_inner_walls;seam_slope_type;sparse_infill_density;sparse_infill_pattern;sparse_infill_speed;spiral_mode;staggered_inner_seams;support_interface_speed;support_speed;top_shell_layers;top_surface_acceleration;top_surface_jerk;top_surface_pattern;top_surface_speed;travel_acceleration;travel_jerk;travel_speed;wall_loops;filament_flow_ratio;nozzle_temperature;deretraction_speed;machine_end_gcode;machine_max_acceleration_e;machine_max_jerk_x;machine_max_jerk_y;machine_max_jerk_z;machine_max_speed_z;machine_start_gcode;printable_area;printable_height;retract_restart_extra;retract_when_changing_layer;retraction_speed;wipe;z_hop;z_hop_types;z_offset
; disable_m73 = 0
; dont_filter_internal_bridges = disabled
; dont_slow_down_outer_wall = 0
; draft_shield = disabled
; during_print_exhaust_fan_speed = 70
; elefant_foot_compensation = 0
; elefant_foot_compensation_layers = 1
; emit_machine_limits_to_gcode = 1
; enable_arc_fitting = 1
; enable_extra_bridge_layer = disabled
; enable_filament_ramming = 1
; enable_long_retraction_when_cut = 0
; enable_overhang_bridge_fan = 1
; enable_overhang_speed = 1
; enable_pressure_advance = 0
; enable_prime_tower = 0
; enable_support = 0
; enforce_support_layers = 0
; eng_plate_temp = 0
; eng_plate_temp_initial_layer = 0
; ensure_vertical_shell_thickness = ensure_all
; exclude_object = 0
; extra_loading_move = -2
; extra_perimeters_on_overhangs = 0
; extra_solid_infills = 
; extruder_clearance_height_to_lid = 140
; extruder_clearance_height_to_rod = 36
; extruder_clearance_radius = 65
; extruder_colour = #26A69A
; extruder_offset = 0x0
; extrusion_rate_smoothing_external_perimeter_only = 0
; fan_cooling_layer_time = 100
; fan_kickstart = 0
; fan_max_speed = 100
; fan_min_speed = 100
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; filament_colour = #26A69A
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 20
; filament_density = 1.24
; filament_diameter = 1.75
; filament_end_gcode = "; filament end gcode\n"
; filament_flow_ratio = 1
; filament_ids = OGFL99
; filament_is_support = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 12
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_when_changing_layer = 0
; filament_settings_id = PLA
; filament_shrink = 100%
; filament_shrinkage_compensation_z = 100%
; filament_soluble = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 0
; filament_start_gcode = "; Filament gcode\n"
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; filename_format = {input_filename_base}_{filament_type[initial_tool]}_{print_time}.gcode
; fill_multiline = 1
; filter_out_gap_fill = 0
; first_layer_print_sequence = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 0.3
; flush_volumes_matrix = 0
; flush_volumes_vector = 140,140
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_first_layer = 0
; fuzzy_skin_mode = displacement
; fuzzy_skin_noise_type = classic
; fuzzy_skin_octaves = 4
; fuzzy_skin_persistence = 0.5
; fuzzy_skin_point_distance = 0.3
; fuzzy_skin_scale = 1
; fuzzy_skin_thickness = 0.2
; gap_fill_target = nowhere
; gap_infill_speed = 40
; gcode_add_line_number = 0
; gcode_comments = 1
; gcode_flavor = marlin
; gcode_label_objects = 1
; has_scarf_joint_seam = 1
; head_wrap_detect_zone = 
; high_current_on_filament_swap = 0
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; hot_plate_temp = 55
; hot_plate_temp_initial_layer = 55
; idle_temperature = 0
; independent_support_layer_height = 1
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 0
; infill_combination_max_layer_height = 100%
; infill_direction = 45
; infill_jerk = 4
; infill_lock_depth = 1
; infill_overhang_angle = 60
; infill_shift_step = 0.4
; infill_wall_overlap = 25%
; inherits_group = "0.20mm Standard @MyMarlin";"Generic PLA @System";"MyMarlin 0.4 nozzle"
; initial_layer_acceleration = 600
; initial_layer_infill_speed = 30
; initial_layer_jerk = 4
; initial_layer_line_width = 0.6
; initial_layer_min_bead_width = 85%
; initial_layer_print_height = 0.2
; initial_layer_speed = 30
; initial_layer_travel_speed = 100%
; inner_wall_acceleration = 600
; inner_wall_jerk = 4
; inner_wall_line_width = 0.45
; inner_wall_speed = 40
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; internal_bridge_angle = 0
; internal_bridge_density = 100%
; internal_bridge_fan_speed = -1
; internal_bridge_flow = 1
; internal_bridge_speed = 150%
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_line_width = 0.4
; internal_solid_infill_pattern = monotonicline
; internal_solid_infill_speed = 40
; ironing_angle = -1
; ironing_fan_speed = -1
; ironing_flow = 10%
; ironing_inset = 0
; ironing_pattern = rectilinear
; ironing_spacing = 0.15
; ironing_speed = 30
; ironing_type = no ironing
; is_infill_first = 0
; lateral_lattice_angle_1 = -45
; lateral_lattice_angle_2 = 45
; layer_change_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; line_width = 0.6
; long_retractions_when_cut = 0
; machine_end_gcode = G1 E-1.0 F2100 ; retract\nG92 E0.0\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nG91 ;\nG1 Z+5 F3000\nG28 X0 Y0 ; park print head\nM84 ; disable motors\nG90 ;
; machine_load_filament_time = 0
; machine_max_acceleration_e = 800
; machine_max_acceleration_extruding = 10000
; machine_max_acceleration_retracting = 1000
; machine_max_acceleration_travel = 0,0
; machine_max_acceleration_x = 10000
; machine_max_acceleration_y = 10000
; machine_max_acceleration_z = 500
; machine_max_jerk_e = 5
; machine_max_jerk_x = 20
; machine_max_jerk_y = 20
; machine_max_jerk_z = 10
; machine_max_junction_deviation = 0,0
; machine_max_speed_e = 60
; machine_max_speed_x = 500
; machine_max_speed_y = 500
; machine_max_speed_z = 20
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; machine_pause_gcode = M601
; machine_start_gcode = G21 ;\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM204 S[machine_max_acceleration_extruding] T[machine_max_acceleration_retracting]\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG92 E0.0\nG28 X0 Y0 ; home\nG28 Z0 ; home\nG1  Z5 F1000 ; move print head up
; machine_tool_change_time = 0
; machine_unload_filament_time = 0
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; manual_filament_change = 0
; max_bridge_length = 10
; max_layer_height = 0.32
; max_resonance_avoidance_speed = 120
; max_travel_detour_distance = 50%
; max_volumetric_extrusion_rate_slope = 0
; max_volumetric_extrusion_rate_slope_segment_length = 3
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.08
; min_length_factor = 0.5
; min_resonance_avoidance_speed = 70
; min_skirt_length = 5
; min_width_top_surface = 300%
; minimum_sparse_infill_area = 15
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; nozzle_height = 2.5
; nozzle_hrc = 0
; nozzle_temperature = 200
; nozzle_temperature_initial_layer = 220
; nozzle_temperature_range_high = 240
; nozzle_temperature_range_low = 190
; nozzle_type = undefine
; nozzle_volume = 0
; only_one_wall_first_layer = 0
; only_one_wall_top = 0
; ooze_prevention = 0
; other_layers_print_sequence = 0
; other_layers_print_sequence_nums = 0
; outer_wall_acceleration = 600
; outer_wall_jerk = 4
; outer_wall_line_width = 0.6
; outer_wall_speed = 60
; overhang_1_4_speed = 0
; overhang_2_4_speed = 50
; overhang_3_4_speed = 30
; overhang_4_4_speed = 10
; overhang_fan_speed = 100
; overhang_fan_threshold = 50%
; overhang_reverse = 0
; overhang_reverse_internal_only = 0
; overhang_reverse_threshold = 50%
; parking_pos_retraction = 92
; pellet_flow_coefficient = 0.4157
; pellet_modded_printer = 0
; post_process = 
; precise_outer_wall = 1
; precise_z_height = 0
; preferred_orientation = 0
; preheat_steps = 1
; preheat_time = 30
; pressure_advance = 0.02
; prime_tower_brim_width = 3
; prime_tower_width = 60
; prime_volume = 45
; print_compatible_printers = "MyMarlin 0.4 nozzle"
; print_flow_ratio = 1
; print_order = default
; print_sequence = by layer
; print_settings_id = 0.20mm Standard @K10
; printable_area = 0x0,100x0,100x100,0x100
; printable_height = 100
; printer_model = Generic Marlin Printer
; printer_notes = 
; printer_settings_id = K10
; printer_structure = undefine
; printer_technology = FFF
; printer_variant = 0.4
; printhost_authorization_type = key
; printhost_ssl_ignore_revoke = 0
; printing_by_object_gcode = 
; purge_in_prime_tower = 1
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 1
; reduce_fan_stop_start_freq = 1
; reduce_infill_retraction = 1
; required_nozzle_HRC = 3
; resolution = 0.012
; resonance_avoidance = 0
; retract_before_wipe = 70%
; retract_length_toolchange = 1
; retract_lift_above = 0
; retract_lift_below = 0
; retract_lift_enforce = All Surfaces
; retract_restart_extra = 0.05
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 0
; retraction_distances_when_cut = 18
; retraction_length = 0.9
; retraction_minimum_travel = 1
; retraction_speed = 50
; role_based_wipe_speed = 1
; scan_first_layer = 0
; scarf_angle_threshold = 155
; scarf_joint_flow_ratio = 1
; scarf_joint_speed = 100%
; scarf_overhang_threshold = 40%
; seam_gap = 10%
; seam_position = nearest
; seam_slope_conditional = 1
; seam_slope_entire_loop = 0
; seam_slope_inner_walls = 1
; seam_slope_min_length = 20
; seam_slope_start_height = 0
; seam_slope_steps = 10
; seam_slope_type = external
; silent_mode = 0
; single_extruder_multi_material = 1
; single_extruder_multi_material_priming = 0
; single_loop_draft_shield = 0
; skeleton_infill_density = 25%
; skeleton_infill_line_width = 100%
; skin_infill_density = 25%
; skin_infill_depth = 2
; skin_infill_line_width = 100%
; skirt_distance = 2
; skirt_height = 1
; skirt_loops = 0
; skirt_speed = 50
; skirt_start_angle = -135
; skirt_type = combined
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1
; slow_down_layer_time = 4
; slow_down_layers = 0
; slow_down_min_speed = 10
; slowdown_for_curled_perimeters = 1
; small_area_infill_flow_compensation = 0
; small_area_infill_flow_compensation_model = 0,0;"\n0.2,0.4444";"\n0.4,0.6145";"\n0.6,0.7059";"\n0.8,0.7619";"\n1.5,0.8571";"\n2,0.8889";"\n3,0.9231";"\n5,0.9520";"\n10,1"
; small_perimeter_speed = 50%
; small_perimeter_threshold = 0
; solid_infill_direction = 45
; solid_infill_filament = 1
; solid_infill_rotate_template = 
; sparse_infill_acceleration = 100%
; sparse_infill_density = 0%
; sparse_infill_filament = 1
; sparse_infill_line_width = 0.45
; sparse_infill_pattern = rectilinear
; sparse_infill_rotate_template = 
; sparse_infill_speed = 40
; spiral_finishing_flow_ratio = 0
; spiral_mode = 1
; spiral_mode_max_xy_smoothing = 200%
; spiral_mode_smooth = 0
; spiral_starting_flow_ratio = 0
; staggered_inner_seams = 1
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; supertack_plate_temp = 45
; supertack_plate_temp_initial_layer = 45
; support_air_filtration = 1
; support_angle = 0
; support_base_pattern = rectilinear
; support_base_pattern_spacing = 2.5
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_chamber_temp_control = 1
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = 2
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_not_for_body = 1
; support_interface_pattern = auto
; support_interface_spacing = 0.5
; support_interface_speed = 30
; support_interface_top_layers = 2
; support_ironing = 0
; support_ironing_flow = 10%
; support_ironing_pattern = rectilinear
; support_ironing_spacing = 0.1
; support_line_width = 0.4
; support_material_interface_fan_speed = -1
; support_multi_bed_types = 0
; support_object_first_layer_gap = 0.2
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_remove_small_overhang = 1
; support_speed = 40
; support_style = default
; support_threshold_angle = 30
; support_threshold_overlap = 50%
; support_top_z_distance = 0.2
; support_type = normal(auto)
; symmetric_infill_y_axis = 0
; temperature_vitrification = 45
; template_custom_gcode = 
; textured_cool_plate_temp = 40
; textured_cool_plate_temp_initial_layer = 40
; textured_plate_temp = 55
; textured_plate_temp_initial_layer = 55
; thick_bridges = 0
; thick_internal_bridges = 1
; thumbnails = 48x48/PNG,300x300/PNG
; thumbnails_format = PNG
; time_cost = 0
; time_lapse_gcode = 
; timelapse_type = 0
; top_bottom_infill_wall_overlap = 25%
; top_shell_layers = 0
; top_shell_thickness = 0.8
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 600
; top_surface_density = 100%
; top_surface_jerk = 4
; top_surface_line_width = 0.4
; top_surface_pattern = monotonic
; top_surface_speed = 40
; travel_acceleration = 600
; travel_jerk = 4
; travel_slope = 3
; travel_speed = 60
; travel_speed_z = 0
; tree_support_adaptive_layer_height = 1
; tree_support_angle_slow = 25
; tree_support_auto_brim = 1
; tree_support_branch_angle = 45
; tree_support_branch_angle_organic = 40
; tree_support_branch_diameter = 5
; tree_support_branch_diameter_angle = 5
; tree_support_branch_diameter_organic = 2
; tree_support_branch_distance = 5
; tree_support_branch_distance_organic = 1
; tree_support_brim_width = 3
; tree_support_tip_diameter = 0.8
; tree_support_top_rate = 30%
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_direction = auto
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = arachne
; wall_loops = 1
; wall_sequence = inner wall/outer wall
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_before_external_loop = 0
; wipe_distance = 1
; wipe_on_loops = 0
; wipe_speed = 80%
; wipe_tower_bridging = 10
; wipe_tower_cone_angle = 30
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_rib_length = 0
; wipe_tower_extra_spacing = 100%
; wipe_tower_filament = 0
; wipe_tower_fillet_wall = 1
; wipe_tower_max_purge_speed = 90
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rib_width = 8
; wipe_tower_rotation_angle = 0
; wipe_tower_wall_type = rectangle
; wipe_tower_x = 165.000
; wipe_tower_x = 165
; wipe_tower_y = 250.000
; wipe_tower_y = 250
; wiping_volumes_extruders = 70,70,70,70,70,70,70,70,70,70
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0.5
; z_hop_types = Auto Lift
; z_offset = 0.35
; first_layer_bed_temperature = 55
; bed_shape = 0x0,100x0,100x100,0x100
; first_layer_temperature = 220
; first_layer_height = 0.200
; CONFIG_BLOCK_END


